
#define KOS_GL_API_OPENGL   0b00001
#define KOS_GL_API_EMBEDDED 0b00010

#define KOS_CONTEXT_SDL2    0b00100
#define KOS_CONTEXT_JAVA    0b01000
#define KOS_CONTEXT_BCM     0b10000

#define KOS_DESKTOP (KOS_CONTEXT_SDL2 | KOS_GL_API_OPENGL)
#define KOS_RPI     (KOS_CONTEXT_BCM  | KOS_GL_API_OPENGL | KOS_GL_API_EMBEDDED)
#define KOS_ANDROID (KOS_CONTEXT_JAVA | KOS_GL_API_OPENGL | KOS_GL_API_EMBEDDED)

#define KOS_CURRENT KOS_DESKTOP

#include "glue.h"
