
#ifndef __AQUA__SDL2_SRC_MACROS_AND_INCLUSIONS_DEVICES_H
	#define __AQUA__SDL2_SRC_MACROS_AND_INCLUSIONS_DEVICES_H
	
	#define DEVICE_NULL     0
	#define DEVICE_TEXTURE  1
	#define DEVICE_KEYBOARD 2
	#define DEVICE_WM       3
	#define DEVICE_MATH     4
	
#endif
